# **NUMPY**

Comparison Of Time Taken

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
my_list=[i for i in range(20000000)]
start_time=process_time()
my_list=[i+6 for i in my_list]
end_time=process_time()
print(end_time-start_time)

1.1907818460000001


In [ ]:
np_array=np.array([i for i in range(20000000)])
start_time=process_time()
np_array+=6
end_time=process_time()
print(end_time-start_time)


0.01765085899999974


Dimension(Row and Column)

In [ ]:
#Single Row(1 dimension)
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [ ]:
#Multiple Row
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
c=np.zeros((4,4))
print(c)

NameError: name 'np' is not defined

In [ ]:
import numpy as np


Initilising List With 0 and **1**

In [ ]:
c=np.zeros((4,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d=np.ones((4,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Intialise with any particular number(like 5)

a=np.full((4,5),6)
print(a)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
#Identity Matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#Array within in range
a=np.arange(4)
print(a)

[0 1 2 3]


Evenly Spaced **Array**

In [16]:
#Evenly Spcaed Array-> By specify the step size

a=np.arange(10,30,5)
print(a)

[10 15 20 25]


In [17]:
#Evenly Spcaed Array-> By specify the Number of Element required
a=np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


Array With Random **Value**

In [12]:
#Create Array with random value betwwen 0 and 1
a=np.random.random((3,4))
print(a)

[[0.3636746  0.01255352 0.92723561 0.28163522]
 [0.94587912 0.62093679 0.82163298 0.90410326]
 [0.94971678 0.75915716 0.04342706 0.92312837]]


In [14]:
#create Random Value between some range(array with element between 10 to 100)

a=np.random.randint(10,100,(3,4))
print(a)

[[46 30 77 97]
 [64 49 10 82]
 [92 49 20 14]]


Conversion of (List,Tuple,Set) into NumPy Array

In [18]:
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

# Analysing The Given Numpy Array

In [19]:
a=np.random.randint(10,90,(4,4))
print(a)

[[74 57 61 87]
 [49 85 83 84]
 [89 85 30 39]
 [29 47 84 33]]


In [20]:
#shape_(row and Column)
print(a.shape)

(4, 4)


In [21]:
#Dimension
print(a.ndim)

2


In [22]:
#Number of Element
print(a.size)

16


In [23]:
#DataType
print(a.dtype)

int64


# Some Mathematical Operations on NumPy Array


In [24]:
#incase of List, (+) will perform concatination
list1=[1,2,3,4]
list2=[5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [26]:
#But we want to do some operation like add,sub,multiply and divide on Numpy Array

a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print(b)


[[7 1 3]
 [4 3 8]
 [2 2 0]]
[[7 5 3]
 [2 4 2]
 [8 5 3]]


In [27]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[14  6  6]
 [ 6  7 10]
 [10  7  3]]
[[ 0 -4  0]
 [ 2 -1  6]
 [-6 -3 -3]]
[[49  5  9]
 [ 8 12 16]
 [16 10  0]]
[[1.   0.2  1.  ]
 [2.   0.75 4.  ]
 [0.25 0.4  0.  ]]


In [32]:
#Another way to do this

a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print(b)


[[2 6 6]
 [7 5 8]
 [4 7 5]]
[[6 6 1]
 [1 2 9]
 [6 3 4]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 8 12  7]
 [ 8  7 17]
 [10 10  9]]
[[-4  0  5]
 [ 6  3 -1]
 [-2  4  1]]
[[12 36  6]
 [ 7 10 72]
 [24 21 20]]
[[0.33333333 1.         6.        ]
 [7.         2.5        0.88888889]
 [0.66666667 2.33333333 1.25      ]]


NumPy Array Manupulation

In [34]:
#Taking Tranpose

a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

Trans=np.transpose(a)
print(Trans)
print(Trans.shape)

[[4 8 4]
 [3 6 5]]
(2, 3)
[[4 3]
 [8 6]
 [4 5]]
(3, 2)


In [35]:
a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

b=a.T
print(b)
print(b.shape)

[[2 5 3]
 [2 5 5]]
(2, 3)
[[2 2]
 [5 5]
 [3 5]]
(3, 2)
