# **Matrices Operation**

In [ ]:
import numpy as np

**Addition**

In [ ]:
a=np.array([[2,3],[4,5]])

b=np.array([[6,7],[8,9]])

print(a)

[[2 3]
 [4 5]]


In [ ]:
print(b)

[[6 7]
 [8 9]]


In [ ]:
sum=a+b
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
#Random Matrices

c=np.random.randint(10, size=(3,3))

d=np.random.randint(20, size=(3,3))

In [ ]:
print(c)

[[6 8 9]
 [3 5 2]
 [6 6 1]]


In [ ]:
print(d)

[[ 7 16 12]
 [14 13  2]
 [14  8  8]]


In [ ]:
#Additing two matrix

sum=np.add(c,d)

print(sum)

[[13 24 21]
 [17 18  4]
 [20 14  9]]


**Substraction**

In [ ]:
a=np.array([[2,3],[4,5]])

b=np.array([[6,7],[8,9]])

In [ ]:
diff=b-a
print(diff)

[[4 4]
 [4 4]]


In [ ]:
#Random Matrices

c=np.random.randint(10, size=(3,3))

d=np.random.randint(20, size=(3,3))

In [19]:
#Subtracting two matrix

diff=np.subtract(c,d)

print(diff)

[[  4   0 -16]
 [-11   2   1]
 [-11   0  -9]]


In [20]:
x=5
y=np.array([[2,3],[4,5]])
b=np.multiply(x,y)
print(b)

[[10 15]
 [20 25]]


In [22]:
d=5*a
print(d)

[[10 15]
 [20 25]]


## **Multiplication of Two matrices**

In [23]:
#Random Matrices

c=np.random.randint(10, size=(3,3))

d=np.random.randint(20, size=(3,3))

In [25]:
ans=np.dot(c,d)
print(ans)

[[ 42  91 126]
 [ 36  88 100]
 [ 14  44  28]]


In [27]:
#Random Matrices

m=np.random.randint(10, size=(3,3))

n=np.random.randint(20, size=(2,3))

ans2=np.dot(m,n)
print(ans2)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Column of first matrix is not equal to row of second matrix

**Element** **wise** **Multiplication**

In [28]:
#Random Matrices

c=np.random.randint(10, size=(3,3))

d=np.random.randint(20, size=(3,3))

ans=np.multiply(c,d)
#ans= c*d

print(ans)

[[24  4  0]
 [ 0 63  6]
 [54 60 16]]
